### ISSUE TITLE
UniformSession feature isn't loaded on .NET Core

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.UniformSession#7]
Because .NET Core doesn't copy assemblies from nuget packages into the bin folder by default, the UniformSession assembly won't be scanned when running a project from VS or via dotnet run without publishing it. Due to the missing scanning, the Feature won't be detected and properly initialized, causing exceptions when trying to inject IUniformSession.

A possible workaround would be an explicit Opt-In API (e.g. `endpointConfiguration.EnableUniformSession()`. This way, the assembly is referenced and loaded before NServiceBus AssemblyScanning takes place and the feature will be properly initialized.

a workaround until this is fixed, is to load the "NServiceBus.UniformSession" assembly manually via Assembly.Load before starting the endpoint.

(v1 should not be affected as this is only an issue with .net core)

cc @danielmarbach

**Comment by danielmarbach** [comment]
This means all plugins that rely solely on scanning and features enabled by default are sort of broken with .NET Core, right? I was actually never a big fan of silently enabled features and I like the explicit opt-in approach much more. Given that this affects many other plugins should we summarize it and RFC a potential solution approach?

**Comment by timbussmann** [comment]
> This means all plugins that rely solely on scanning and features enabled by default are sort of broken with .NET Core, right?

yes. Issue was raised in the launch project about this.

> Given that this affects many other plugins should we summarize it and RFC a potential solution approach?

we might want to await the outcome of https://github.com/Particular/DotNetCoreLaunch/issues/90 and then decide the next steps?
